SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE latrobe_d8765_notification_recipients;
TRUNCATE latrobe_d8765_notification_groups;
TRUNCATE latrobe_d8765_notifications;
SET FOREIGN_KEY_CHECKS = 1;
TRUNCATE southam_v4_shared4.shared_s3v3_process_notification_groups;