CREATE TABLE IF NOT EXISTS products (
    id INT PRIMARY KEY AUTO_INCREMENT,
    category_id INT(11) NULL DEFAULT '0',
    title VARCHAR(250) NOT NULL,
    slug VARCHAR(250) NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    price DECIMAL(30,5) NOT NULL DEFAULT '0.00',
    image VARCHAR(250) NOT NULL DEFAULT '',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP
);