DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
     id INT PRIMARY KEY AUTO_INCREMENT,
     `uuid` VARCHAR(255) NOT NULL DEFAULT (uuid()),
     name VARCHAR(300) NOT NULL CHECK ( LENGTH(name) > 2 ),
     age INT CHECK (age > 0),
     created DATETIME DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME ON UPDATE CURRENT_TIMESTAMP,
     INDEX uuid (uuid)
);
